version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 8124:8124
    volumes:
      - ./:/usr/src/app
    environment: 
      MONGODB_ADMIN_USERNAME: root
      MONGODB_ADMIN_PASSWORD: password
      MONGODB_PORT: 27017

  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment: 
      MONGO_INITDB_DATABASE: parking-lot


      
volumes:
  mongodb: